apiVersion: v1
kind: ServiceAccount
metadata:
  name: policy-docs
  namespace: policy-docs
  labels:
    app.kubernetes.io/name: policy-docs
    app.kubernetes.io/part-of: ggi-policy
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth2-proxy
  namespace: policy-docs
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: ggi-policy
automountServiceAccountToken: false
